### ISSUE TITLE
Unauthorized Access using akamai_appsec_security_policy

### ISSUE THREAD

**Issue by peteneville** [akamai/terraform-provider-akamai#225]
### Versions
Terraform 0.12.26
Tried Akamai provider version 1.4.0 and now moved to 1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_appsec_security_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "akamai_appsec_security_policy" "policy" {
  config_id              = data.akamai_appsec_configuration.configuration.config_id
  version                = data.akamai_appsec_configuration.configuration.latest_version
  default_settings       = var.default_settings
  security_policy_name   = var.security_policy_name
  security_policy_prefix = var.security_policy_prefix  
}
```

### Expected Behavior
Application security policy should have been created within the existing configuration

### Actual Behavior
The following error:
```
akamai_appsec_security_policy.policy: Creating...
akamai_property.property: Modifying... [id=prp_699458]
akamai_property.property: Modifications complete after 9s [id=prp_699458]

Error: Title: Unauthorized Access/Action; Type: https://problems.luna.akamaiapis.net/appsec/error-types/UNAUTHORIZED; Detail: You do not have the necessary access to perform this operation.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I have set up the API user with the following permissions:
Application Security READ-WRITE
Property Manager (PAPI) READ-WRITE

I have also tried all access levels

It is not clear what access level is required or why I am not authorized. I can create the policy in the web console.

### References
None found

**Comment by atuljain16** [comment]
Plz provide the account details.

**Comment by peteneville** [comment]
> Plz provide the account details.

The account is NHS Digital. If you need the contract id etc, please can you provide an email address, rather than post that here? 

Thanks

**Comment by peteneville** [comment]
Same error for when I use akamai_appsec_configuration_version_clone or akamai_appsec_security_policy_clone.
However, it looks like akamai_appsec_security_policy_clone was partially successful as I now have a new policy that I can see in the web console. The state file shows this as tainted though.

**Comment by peteneville** [comment]
Also tried akamai_appsec_match_target. This has allowed me to add match targets to the policy that I have cloned. i.e. the tainted policy that I have now removed from state, but still exists and I can use on subsequent terraform.
If only we can get past these authZ errors..
Also, I could do with some examples of json for akamai_appsec_rule_condition_exception as this is what I'd like to start using next. I've used the datasoruce akamai_appsec_export_configuration to export all as json, but it's not entirely clear for exceptions what the json should be. e.g. all ruleActions including exceptions or just the ones with exceptions.

**Comment by lkowalsk-akamai-com** [comment]
We believe the issue was lack of enrolled in the BETA program, which should now be resolved. @peteneville please confirm if all is good now and close the case.

**Comment by peteneville** [comment]
Thanks. I still get the error "Error: Title: Unauthorized Access/Action; Type: https://problems.luna.akamaiapis.net/appsec/error-types/UNAUTHORIZED; Detail: You do not have the necessary access to perform this operation." when using the resource akamai_appsec_configuration_version_clone on a configuration version that was created by another user. 
Using new configurations that I create work though. I'm working with Akamai support via our contract so can close the ticket here if that helps?

**Comment by lkowalsk-akamai-com** [comment]
Since this looks like a authorization issue that will not require a coding change I will close the ticket. Please continue directly with Akamai Support. Hope you will have it resolved quickly!
